var json_NaturbelasseneTeilflchen_5 = {
"type": "FeatureCollection",
"name": "NaturbelasseneTeilflchen_5",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "id": null, "Name": null, "descriptio": "Beschreibung: <br>link: <br>Naturnaehe: <br>Landschaft: <br>Zersiedelu: <br>Freizform: <br>NNaeheZ: <br>LBZahl: <br>ZersZahl: <br>GogglBew:", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null, "Beschreibu": null, "link": null, "Naturnaehe": null, "Landschaft": null, "Zersiedelu": null, "Freizform": null, "NNaeheZ": null, "LBZahl": null, "ZersZahl": null, "GogglBew": null }, "geometry": { "type": "Point", "coordinates": [ 11.160957, 47.152095 ] } },
{ "type": "Feature", "properties": { "id": null, "Name": null, "descriptio": "Beschreibung: <br>link: <br>Naturnaehe: <br>Landschaft: <br>Zersiedelu: <br>Freizform: <br>NNaeheZ: <br>LBZahl: <br>ZersZahl: <br>GogglBew:", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null, "Beschreibu": null, "link": null, "Naturnaehe": null, "Landschaft": null, "Zersiedelu": null, "Freizform": null, "NNaeheZ": null, "LBZahl": null, "ZersZahl": null, "GogglBew": null }, "geometry": { "type": "Point", "coordinates": [ 12.558578, 46.691757 ] } },
{ "type": "Feature", "properties": { "id": null, "Name": null, "descriptio": "Beschreibung: <br>link: <br>Naturnaehe: <br>Landschaft: <br>Zersiedelu: <br>Freizform: <br>NNaeheZ: <br>LBZahl: <br>ZersZahl: <br>GogglBew:", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null, "Beschreibu": null, "link": null, "Naturnaehe": null, "Landschaft": null, "Zersiedelu": null, "Freizform": null, "NNaeheZ": null, "LBZahl": null, "ZersZahl": null, "GogglBew": null }, "geometry": { "type": "Point", "coordinates": [ 12.674063, 46.730248 ] } },
{ "type": "Feature", "properties": { "id": null, "Name": null, "descriptio": "Beschreibung: <br>link: <br>Naturnaehe: <br>Landschaft: <br>Zersiedelu: <br>Freizform: <br>NNaeheZ: <br>LBZahl: <br>ZersZahl: <br>GogglBew:", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null, "Beschreibu": null, "link": null, "Naturnaehe": null, "Landschaft": null, "Zersiedelu": null, "Freizform": null, "NNaeheZ": null, "LBZahl": null, "ZersZahl": null, "GogglBew": null }, "geometry": { "type": "Point", "coordinates": [ 12.417423, 46.825929 ] } },
{ "type": "Feature", "properties": { "id": null, "Name": null, "descriptio": "Beschreibung: <br>link: <br>Naturnaehe: <br>Landschaft: <br>Zersiedelu: <br>Freizform: <br>NNaeheZ: <br>LBZahl: <br>ZersZahl: <br>GogglBew:", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null, "Beschreibu": null, "link": null, "Naturnaehe": null, "Landschaft": null, "Zersiedelu": null, "Freizform": null, "NNaeheZ": null, "LBZahl": null, "ZersZahl": null, "GogglBew": null }, "geometry": { "type": "Point", "coordinates": [ 12.4279637, 46.877029 ] } },
{ "type": "Feature", "properties": { "id": null, "Name": null, "descriptio": "Beschreibung: <br>link: <br>Naturnaehe: <br>Landschaft: <br>Zersiedelu: <br>Freizform: <br>NNaeheZ: <br>LBZahl: <br>ZersZahl: <br>GogglBew:", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null, "Beschreibu": null, "link": null, "Naturnaehe": null, "Landschaft": null, "Zersiedelu": null, "Freizform": null, "NNaeheZ": null, "LBZahl": null, "ZersZahl": null, "GogglBew": null }, "geometry": { "type": "Point", "coordinates": [ 13.163264, 46.850702 ] } },
{ "type": "Feature", "properties": { "id": null, "Name": "Alte Fischaschlingen", "descriptio": "Beschreibung: <br>link: https://www.noe-naturschutzbund.at/alte-fischaschlingen.html<br>Naturnaehe: <br>Landschaft: <br>Zersiedelu: <br>Freizform: <br>NNaeheZ: <br>LBZahl: <br>ZersZahl: <br>GogglBew:", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null, "Beschreibu": null, "link": "https://www.noe-naturschutzbund.at/alte-fischaschlingen.html", "Naturnaehe": null, "Landschaft": null, "Zersiedelu": null, "Freizform": null, "NNaeheZ": null, "LBZahl": null, "ZersZahl": null, "GogglBew": null }, "geometry": { "type": "Point", "coordinates": [ 16.512783, 48.032096 ] } },
{ "type": "Feature", "properties": { "id": null, "Name": "Naturbelassene Fläche, nicht klar abgegrenzt", "descriptio": "Beschreibung: <br>link: <br>Naturnaehe: <br>Landschaft: <br>Zersiedelu: <br>Freizform: <br>NNaeheZ: <br>LBZahl: <br>ZersZahl: <br>GogglBew:", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null, "Beschreibu": null, "link": null, "Naturnaehe": null, "Landschaft": null, "Zersiedelu": null, "Freizform": null, "NNaeheZ": null, "LBZahl": null, "ZersZahl": null, "GogglBew": null }, "geometry": { "type": "Point", "coordinates": [ 15.61652, 47.760779 ] } },
{ "type": "Feature", "properties": { "id": null, "Name": "Naturbelassene Fläche Eisenerzer Reichenstein", "descriptio": "Beschreibung: <br>link: <br>Naturnaehe: <br>Landschaft: <br>Zersiedelu: <br>Freizform: <br>NNaeheZ: <br>LBZahl: <br>ZersZahl: <br>GogglBew:", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null, "Beschreibu": null, "link": null, "Naturnaehe": null, "Landschaft": null, "Zersiedelu": null, "Freizform": null, "NNaeheZ": null, "LBZahl": null, "ZersZahl": null, "GogglBew": null }, "geometry": { "type": "Point", "coordinates": [ 14.817526, 47.537713 ] } },
{ "type": "Feature", "properties": { "id": null, "Name": "Naturbelassene Fläche", "descriptio": "Beschreibung: <br>link: <br>Naturnaehe: <br>Landschaft: <br>Zersiedelu: <br>Freizform: <br>NNaeheZ: <br>LBZahl: <br>ZersZahl: <br>GogglBew:", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null, "Beschreibu": null, "link": null, "Naturnaehe": null, "Landschaft": null, "Zersiedelu": null, "Freizform": null, "NNaeheZ": null, "LBZahl": null, "ZersZahl": null, "GogglBew": null }, "geometry": { "type": "Point", "coordinates": [ 14.721613, 47.488862 ] } },
{ "type": "Feature", "properties": { "id": null, "Name": null, "descriptio": "Beschreibung: <br>link: <br>Naturnaehe: <br>Landschaft: <br>Zersiedelu: <br>Freizform: <br>NNaeheZ: <br>LBZahl: <br>ZersZahl: <br>GogglBew:", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null, "Beschreibu": null, "link": null, "Naturnaehe": null, "Landschaft": null, "Zersiedelu": null, "Freizform": null, "NNaeheZ": null, "LBZahl": null, "ZersZahl": null, "GogglBew": null }, "geometry": { "type": "Point", "coordinates": [ 11.423552, 47.008214 ] } },
{ "type": "Feature", "properties": { "id": null, "Name": null, "descriptio": "Beschreibung: <br>link: <br>Naturnaehe: <br>Landschaft: <br>Zersiedelu: <br>Freizform: <br>NNaeheZ: <br>LBZahl: <br>ZersZahl: <br>GogglBew:", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null, "Beschreibu": null, "link": null, "Naturnaehe": null, "Landschaft": null, "Zersiedelu": null, "Freizform": null, "NNaeheZ": null, "LBZahl": null, "ZersZahl": null, "GogglBew": null }, "geometry": { "type": "Point", "coordinates": [ 11.593791, 47.036973 ] } },
{ "type": "Feature", "properties": { "id": null, "Name": null, "descriptio": "Beschreibung: <br>link: <br>Naturnaehe: <br>Landschaft: <br>Zersiedelu: <br>Freizform: <br>NNaeheZ: <br>LBZahl: <br>ZersZahl: <br>GogglBew:", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null, "Beschreibu": null, "link": null, "Naturnaehe": null, "Landschaft": null, "Zersiedelu": null, "Freizform": null, "NNaeheZ": null, "LBZahl": null, "ZersZahl": null, "GogglBew": null }, "geometry": { "type": "Point", "coordinates": [ 13.686027, 46.933971 ] } },
{ "type": "Feature", "properties": { "id": null, "Name": null, "descriptio": "Beschreibung: <br>link: <br>Naturnaehe: <br>Landschaft: <br>Zersiedelu: <br>Freizform: <br>NNaeheZ: <br>LBZahl: <br>ZersZahl: <br>GogglBew:", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null, "Beschreibu": null, "link": null, "Naturnaehe": null, "Landschaft": null, "Zersiedelu": null, "Freizform": null, "NNaeheZ": null, "LBZahl": null, "ZersZahl": null, "GogglBew": null }, "geometry": { "type": "Point", "coordinates": [ 11.404993, 47.398701 ] } },
{ "type": "Feature", "properties": { "id": null, "Name": null, "descriptio": "Beschreibung: <br>link: <br>Naturnaehe: <br>Landschaft: <br>Zersiedelu: <br>Freizform: <br>NNaeheZ: <br>LBZahl: <br>ZersZahl: <br>GogglBew:", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null, "Beschreibu": null, "link": null, "Naturnaehe": null, "Landschaft": null, "Zersiedelu": null, "Freizform": null, "NNaeheZ": null, "LBZahl": null, "ZersZahl": null, "GogglBew": null }, "geometry": { "type": "Point", "coordinates": [ 11.377516, 47.353138 ] } },
{ "type": "Feature", "properties": { "id": null, "Name": null, "descriptio": "Beschreibung: <br>link: <br>Naturnaehe: <br>Landschaft: <br>Zersiedelu: <br>Freizform: <br>NNaeheZ: <br>LBZahl: <br>ZersZahl: <br>GogglBew:", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null, "Beschreibu": null, "link": null, "Naturnaehe": null, "Landschaft": null, "Zersiedelu": null, "Freizform": null, "NNaeheZ": null, "LBZahl": null, "ZersZahl": null, "GogglBew": null }, "geometry": { "type": "Point", "coordinates": [ 11.493177, 47.43606 ] } },
{ "type": "Feature", "properties": { "id": null, "Name": null, "descriptio": "Beschreibung: <br>link: <br>Naturnaehe: <br>Landschaft: <br>Zersiedelu: <br>Freizform: <br>NNaeheZ: <br>LBZahl: <br>ZersZahl: <br>GogglBew:", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null, "Beschreibu": null, "link": null, "Naturnaehe": null, "Landschaft": null, "Zersiedelu": null, "Freizform": null, "NNaeheZ": null, "LBZahl": null, "ZersZahl": null, "GogglBew": null }, "geometry": { "type": "Point", "coordinates": [ 11.539221, 47.47408 ] } },
{ "type": "Feature", "properties": { "id": null, "Name": "Hohenzollernhaus 2123m", "descriptio": "Beschreibung: <br>link: <br>Naturnaehe: hoch<br>Landschaft: 3000er Bergregion<br>Zersiedelu: im unteren Bereich ja<br>Freizform: Rad + Wandern<br>NNaeheZ: 3<br>LBZahl: 3<br>ZersZahl: 1<br>GogglBew:", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null, "Beschreibu": null, "link": null, "Naturnaehe": "hoch", "Landschaft": "3000er Bergregion", "Zersiedelu": "im unteren Bereich ja", "Freizform": "Rad + Wandern", "NNaeheZ": "3", "LBZahl": "3", "ZersZahl": "1", "GogglBew": null }, "geometry": { "type": "Point", "coordinates": [ 10.633808, 46.899442 ] } },
{ "type": "Feature", "properties": { "id": null, "Name": "Hochjochhospiz 2413m", "descriptio": "Beschreibung: <br>link: <br>Naturnaehe: hoch<br>Landschaft: Tal2000<br>Zersiedelu: <br>Freizform: Wandern<br>NNaeheZ: 3<br>LBZahl: 3<br>ZersZahl: <br>GogglBew: 47", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null, "Beschreibu": null, "link": null, "Naturnaehe": "hoch", "Landschaft": "Tal2000", "Zersiedelu": null, "Freizform": "Wandern", "NNaeheZ": "3", "LBZahl": "3", "ZersZahl": null, "GogglBew": "47" }, "geometry": { "type": "Point", "coordinates": [ 10.833912, 46.82508 ] } }
]
}
