var json_RuhigeGebieteinsterreich_13 = {
"type": "FeatureCollection",
"name": "RuhigeGebieteinsterreich_13",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Neusiedler See", "descriptio": "besonders ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 16.7775594, 47.8650427 ] } },
{ "type": "Feature", "properties": { "Name": "Schilfzone Neusiedlersee", "descriptio": "sehr ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 16.7147214, 47.8854641 ] } },
{ "type": "Feature", "properties": { "Name": "Leithagebirge", "descriptio": "ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 16.6666667, 47.9666667 ] } },
{ "type": "Feature", "properties": { "Name": "Arbesthaler Hügelland", "descriptio": "ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 16.7210865, 48.0895846 ] } },
{ "type": "Feature", "properties": { "Name": "Nationalpark Donau-Auen", "descriptio": "ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 16.7353732, 48.1339067 ] } },
{ "type": "Feature", "properties": { "Name": "Wolfsthal", "descriptio": "ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 17.0101937, 48.1185559 ] } },
{ "type": "Feature", "properties": { "Name": "Marchfeld Ost", "descriptio": "ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 16.9543136, 48.183612 ] } },
{ "type": "Feature", "properties": { "Name": "Gänserndorf bei Erlebnispark", "descriptio": "ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 16.7426016, 48.2959176 ] } },
{ "type": "Feature", "properties": { "Name": "Punkt 8", "descriptio": "ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 16.579434, 48.4015955 ] } },
{ "type": "Feature", "properties": { "Name": "Punkt 9", "descriptio": "ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 16.7224279, 48.4229029 ] } },
{ "type": "Feature", "properties": { "Name": "Großmittel", "descriptio": "ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 16.3047288, 47.8873515 ] } },
{ "type": "Feature", "properties": { "Name": "Marzer Kogel", "descriptio": "ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 16.4732532, 47.727105 ] } },
{ "type": "Feature", "properties": { "Name": "Rohrbach Wald", "descriptio": "ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 16.4289645, 47.680203 ] } },
{ "type": "Feature", "properties": { "Name": "Ritzing Wald", "descriptio": "ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 16.478403, 47.638117 ] } },
{ "type": "Feature", "properties": { "Name": "Bucklige Welt", "descriptio": "ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 16.2277774, 47.6015534 ] } },
{ "type": "Feature", "properties": { "Name": "Fischbacher Alpen", "descriptio": "ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 15.7476286, 47.4574091 ] } },
{ "type": "Feature", "properties": { "Name": "Hochschwab", "descriptio": "sehr ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 15.0870748, 47.5915656 ] } },
{ "type": "Feature", "properties": { "Name": "Punkt 18", "descriptio": "sehr ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 15.0671629, 47.6896508 ] } },
{ "type": "Feature", "properties": { "Name": "Hochkar", "descriptio": "sehr ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 14.9175, 47.71906 ] } },
{ "type": "Feature", "properties": { "Name": "Nationalpark Gesäuse GmbH", "descriptio": "sehr ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 14.5891131999999, 47.5652076 ] } },
{ "type": "Feature", "properties": { "Name": "Punkt 19", "descriptio": "besonders ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 14.2209749, 47.6448371 ] } },
{ "type": "Feature", "properties": { "Name": "Punkt 20", "descriptio": "besonders ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 14.0547495, 47.6352275 ] } },
{ "type": "Feature", "properties": { "Name": "Großer Priel", "descriptio": "besonders ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 14.0642265, 47.7170829 ] } },
{ "type": "Feature", "properties": { "Name": "Punkt 21", "descriptio": "besonders ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 14.0233355, 47.5197962 ] } },
{ "type": "Feature", "properties": { "Name": "Dachstein", "descriptio": "besonders ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 13.6056386, 47.4751344 ] } },
{ "type": "Feature", "properties": { "Name": "Fritzerkogel", "descriptio": "besonders ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 13.2666158, 47.5210837 ] } },
{ "type": "Feature", "properties": { "Name": "Hochkönig", "descriptio": "besonders ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 13.0324205, 47.4582811 ] } },
{ "type": "Feature", "properties": { "Name": "Rax", "descriptio": "sehr ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 15.7128007, 47.7018673 ] } },
{ "type": "Feature", "properties": { "Name": "Gutenmann", "descriptio": "ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 15.9990926, 47.760489 ] } },
{ "type": "Feature", "properties": { "Name": "Rosaliengebirge", "descriptio": "ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 16.2874838, 47.7360192 ] } },
{ "type": "Feature", "properties": { "Name": "Hohe Wand", "descriptio": "ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 16.0410411, 47.836563 ] } },
{ "type": "Feature", "properties": { "Name": "Hart", "descriptio": "ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 16.1519343, 47.8950654 ] } },
{ "type": "Feature", "properties": { "Name": "Gutensteiner Alpen", "descriptio": "ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 15.8999354, 47.9536711 ] } },
{ "type": "Feature", "properties": { "Name": "Merkenstein Lindkogel", "descriptio": "ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 16.1328799, 47.9984888 ] } },
{ "type": "Feature", "properties": { "Name": "Gumpolsdkirchen Pfaffstätten", "descriptio": "ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 16.247378, 48.0549725 ] } },
{ "type": "Feature", "properties": { "Name": "Sparbach", "descriptio": "ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 16.2041194, 48.1049755 ] } },
{ "type": "Feature", "properties": { "Name": "Gemeinde Wienerwald Nord", "descriptio": "ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 16.086703, 48.1301879 ] } },
{ "type": "Feature", "properties": { "Name": "Triestingtal Nord", "descriptio": "ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 15.8175216, 48.0971691 ] } },
{ "type": "Feature", "properties": { "Name": "Punkt 34", "descriptio": "ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 15.4954848, 47.9952615 ] } },
{ "type": "Feature", "properties": { "Name": "Irenental", "descriptio": "ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 16.1017928, 48.2162642 ] } },
{ "type": "Feature", "properties": { "Name": "Punkt 36", "descriptio": "besonders ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 13.4994416, 47.2044804 ] } },
{ "type": "Feature", "properties": { "Name": "Punkt 37", "descriptio": "sehr ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 13.7505102, 47.3013064 ] } },
{ "type": "Feature", "properties": { "Name": "Punkt 38", "descriptio": "besonders ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 14.3904638, 47.4514955 ] } },
{ "type": "Feature", "properties": { "Name": "Ankogelgruppe", "descriptio": "besonders ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 13.3199999, 47.02 ] } },
{ "type": "Feature", "properties": { "Name": "Mölltaler Gletscher", "descriptio": "besonders ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 13.0047695, 47.0056418 ] } },
{ "type": "Feature", "properties": { "Name": "Großglockner", "descriptio": "besonders ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 12.6946761, 47.0741851 ] } },
{ "type": "Feature", "properties": { "Name": "Großvenediger", "descriptio": "besonders ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 12.3464665, 47.1091466 ] } },
{ "type": "Feature", "properties": { "Name": "Punkt 39", "descriptio": "besonders ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 12.4886274, 46.8505532 ] } },
{ "type": "Feature", "properties": { "Name": "Gailtaler Alpen", "descriptio": "besonders ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 12.811667, 46.766667 ] } },
{ "type": "Feature", "properties": { "Name": "Punkt 40", "descriptio": "sehr ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 13.0977843, 46.8435188 ] } },
{ "type": "Feature", "properties": { "Name": "Punkt 41", "descriptio": "besonders ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 11.9269153, 47.0517022 ] } },
{ "type": "Feature", "properties": { "Name": "Punkt 42", "descriptio": "besonders ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 11.7030688, 47.0381331 ] } },
{ "type": "Feature", "properties": { "Name": "Stubaital", "descriptio": "besonders ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 11.1255999, 47.0605903 ] } },
{ "type": "Feature", "properties": { "Name": "Ötztaler Alpen", "descriptio": "besonders ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 10.9048932, 46.8129921 ] } },
{ "type": "Feature", "properties": { "Name": "Punkt 44", "descriptio": "besonders ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 10.8124896, 46.9688306 ] } },
{ "type": "Feature", "properties": { "Name": "Punkt 45", "descriptio": "besonders ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 10.4828998, 47.0353253 ] } },
{ "type": "Feature", "properties": { "Name": "Piz Buin", "descriptio": "besonders ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 10.1188827999999, 46.8441753 ] } },
{ "type": "Feature", "properties": { "Name": "Punkt 46", "descriptio": "besonders ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 10.2302142, 47.0727507 ] } },
{ "type": "Feature", "properties": { "Name": "Schesaplana", "descriptio": "besonders ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 9.707267, 47.0538479 ] } },
{ "type": "Feature", "properties": { "Name": "Punkt 47", "descriptio": "besonders ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 10.0326597, 47.2077988 ] } },
{ "type": "Feature", "properties": { "Name": "Punkt 48", "descriptio": "besonders ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 10.6300413, 47.2572212 ] } },
{ "type": "Feature", "properties": { "Name": "Punkt 49", "descriptio": "besonders ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 10.4429725, 47.3370344 ] } },
{ "type": "Feature", "properties": { "Name": "Punkt 50", "descriptio": "besonders ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 10.9758094, 47.3575049 ] } },
{ "type": "Feature", "properties": { "Name": "Punkt 51", "descriptio": "besonders ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 11.5013796, 47.3868657 ] } },
{ "type": "Feature", "properties": { "Name": "Punkt 52", "descriptio": "ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 11.9694269, 47.5403608 ] } },
{ "type": "Feature", "properties": { "Name": "Punkt 53", "descriptio": "ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 12.1534479, 47.3406621 ] } },
{ "type": "Feature", "properties": { "Name": "Punkt 54", "descriptio": "besonders ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 12.3132685, 47.5639078 ] } },
{ "type": "Feature", "properties": { "Name": "Punkt 55", "descriptio": "besonders ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 12.5975397, 47.5425905 ] } },
{ "type": "Feature", "properties": { "Name": "Punkt 56", "descriptio": "besonders ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 12.7376154, 47.482299 ] } },
{ "type": "Feature", "properties": { "Name": "Wolfsgeist", "descriptio": "ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 16.0988618, 47.983562 ] } },
{ "type": "Feature", "properties": { "Name": "Siegendorfer Puszta", "descriptio": "ruhig", "Kategorie": "Ruhige Gebiete" }, "geometry": { "type": "Point", "coordinates": [ 16.599148, 47.761735 ] } }
]
}
